version: '3.7'

services:
    db:
        image: mysql:5.6
        ports:
            - "3333:3306"
        environment:
            MYSQL_ROOT_PASSWORD: apple
        volumes:
            - ./mysql_directory:/var/lib/mysql
        networks:
            - beliikan-web

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8800:80"
        links:
            - db
        networks:
            - beliikan-web
            
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: 'beliikan/laravel'
        container_name: beliikan-web
        ports:
            - "9001:80"
        volumes:
            - ./:/var/www/html
        links:
            - db
        networks:
            - beliikan-web
networks:
    beliikan-web:
        driver: bridge
